sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

script:
- cargo test
- cargo build --manifest-path=examples/hello_world/Cargo.toml
- cargo build --manifest-path=examples/lists/Cargo.toml