[package]
name = "pickledb"
version = "0.1.0"
authors = ["seladb <pcapplusplus@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.82"
serde_json = "1.0"
serde_derive = "1.0"

[dev-dependencies]
rand = "0.6.3"
