[package]
name = "pickledb"
version = "0.2.0"
authors = ["seladb <pcapplusplus@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "A lightweight and simple key-value store written in Rust, heavily inspired by [Python's PickleDB](https://pythonhosted.org/pickleDB/)"
repository = "https://github.com/seladb/pickledb-rs"
homepage = "https://github.com/seladb/pickledb-rs"
documentation = "http://docs.rs/pickledb"
keywords = ["database", "key-value-store", "db", "kv", "pickledb"]
categories = ["database-implementations", "data-structures"]
edition = "2018"

[badges]
travis-ci = { repository = "seladb/pickledb-rs" }

[dependencies]
serde = "1.0.82"
serde_json = "1.0"
serde_derive = "1.0"
bincode = "1.0.1"
serde_yaml = "0.8.8"

[dev-dependencies]
rand = "0.6.3"
rstest = "0.2.2"
