[package]
name = "pickledb_lists_example"
version = "0.1.0"
authors = ["seladb <pcapplusplus@gmail.com>"]
edition = "2018"

[dependencies]
pickledb = { path = "../../" }
serde = "1.0.82"
serde_derive = "1.0"
